### ISSUE TITLE
npm run test failed 

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-antenna#114]
when using  host 35.239.122.109:80 
![DeepinScreenshot_select-area_20190403145944](https://user-images.githubusercontent.com/12439992/55459481-4485b180-5622-11e9-9441-106b717656a1.png)

when using  host api.iotex.one:80 
![DeepinScreenshot_select-area_20190403150319](https://user-images.githubusercontent.com/12439992/55459509-55362780-5622-11e9-92a0-4130906a4dc3.png)

**Comment by puncsky** [comment]
https://github.com/iotexproject/iotex-antenna/commit/4d164ba125927d13893b860f3db59e9ec364cf21
