### ISSUE TITLE
add getChainMeta in browser-rpc-method.js

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-antenna#15]
@xiaxiangzhou please do not work on this.

implement the browser version of https://github.com/iotexproject/iotex-antenna/blob/master/src/proto/api.proto#L34 and add tests to https://github.com/iotexproject/iotex-antenna/blob/master/src/rpc-method/__test__/browser-rpc-method.test.js

please refer to other examples in browser-rpc-method.js, and use backend endpoint http://35.192.119.63:31501

**Comment by knightcnbj** [comment]
I got a question about implementing `getChainMeta` function, 
do we need to implement a `GetChainMetaRequest` class in types.js? (I'm trying to follow the way `getBlockMetas` is written)

**Comment by knightcnbj** [comment]
Hi this is Jianyi, I'm trying to push my branch to remote but i dont have access, can someone add me to the repo?

**Comment by knightcnbj** [comment]
I added the `getChainMeta` function in browser-rpc-method.js
along with `GetChainMetaRequest` class in types.js, but I don't really understand the epoch in IChainMeta class, can you guys check if i'm on the right direction once I push my branch?

**Comment by puncsky** [comment]
> Hi this is Jianyi, I'm trying to push my branch to remote but i dont have access, can someone add me to the repo?

sorry being late... added you to the project
