### ISSUE TITLE
implement getBlockMetas in iotex-antenna/src/rpc-method/browser-rpc-method.js

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-antenna#20]
implement getBlockMetas in iotex-antenna/src/rpc-method/browser-rpc-method.js. please test against http://35.192.119.63:31501 in iotex-antenna/src/rpc-method/__test__/browser-rpc-method.test.js

you can refer test examples in rpc-method directory

**Comment by xiaxiangzhou** [comment]
seems we already implement it in browser-rpc-method.js, getBlockMetas

**Comment by xiaxiangzhou** [comment]
@puncsky

**Comment by puncsky** [comment]
nope, node-rpc-method.js and browser-rpc-method.js are different

**Comment by puncsky** [comment]
they run in node / browser environments and have different dependencies
