### ISSUE TITLE
https provider

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-antenna#315]
try new Antenna("https://api.iotex.one") or new Antenna("https://iotexscan.io/iotex-core-proxy") in the browser environment

how to prepare the environment?

go to https://onefx.js.org/doc.html#create-a-project and after creating a project. install iotex-antenna and try to run it in main.ts.

**Comment by ququzone** [comment]
use https provider can use `const antenna = new Antenna("https://api.iotex.one");` directly

**Comment by puncsky** [comment]
awesome, thanks!
