### ISSUE TITLE
server unavailable when calling a certain contract

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-antenna#323]
![31566238683_ pic_hd](https://user-images.githubusercontent.com/1387285/63292711-23dd9180-c27b-11e9-9c27-81456bfaae4c.jpg)

**Comment by ququzone** [comment]
`from` parameter for `antenna.iotx.readContractByMethod` should be valid address.
can change code below:
```ts
const result = await antenna.iotx.readContractByMethod({
    from: BITX_ADDRESS,
    contractAddress: BITX_ADDRESS,
    abi: ABI,
    method: "totalUserNum",
  });
```
