### ISSUE TITLE
amount did not work in iotexscan

### ISSUE THREAD

**Issue by xiaxiangzhou** [iotexproject/iotex-antenna#341]
when I want to deploy a contract and set an amount. The amount shows on the execution is still 0, like this one https://testnet.iotexscan.io/action/a29bc20d98c1cd347a353dd8d8afb05be2aa24f6e65e3c9a0020a74410730305. It end up with deploy failure due to amount is 0.

**Comment by nmhung1210** [comment]
@xiaxiangzhou could you please help to provide more details regarding ABI, bytecode?

**Comment by xiaxiangzhou** [comment]
ABI:
[
	{
		"constant": true,
		"inputs": [],
		"name": "seller",
		"outputs": [
			{
				"name": "",
				"type": "address"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "validMaxBenefit",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [],
		"name": "settle",
		"outputs": [],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getStartReportInterval",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [],
		"name": "cancelContract",
		"outputs": [],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getFrozenInterval",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "reportFlightStatus",
				"type": "uint8"
			}
		],
		"name": "oracleReportStatus",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "flightStatus",
		"outputs": [
			{
				"name": "",
				"type": "uint8"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "buyer",
		"outputs": [
			{
				"name": "",
				"type": "address"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getEndReportInterval",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getEndDisputeInterval",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "oracleAddress",
		"outputs": [
			{
				"name": "",
				"type": "address"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "updatedFlightStatus",
				"type": "uint8"
			}
		],
		"name": "oracleChangeStatus",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "maxBenefit",
				"type": "uint256"
			}
		],
		"name": "adjustMaxBenefit",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "scheduleTakeOffTime",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "contractStatus",
		"outputs": [
			{
				"name": "",
				"type": "uint8"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "validAirlineCode",
		"outputs": [
			{
				"name": "",
				"type": "bytes32"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getPremium",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "maxBenefit",
				"type": "uint256"
			},
			{
				"name": "status",
				"type": "uint8"
			}
		],
		"name": "getBenefitByFlightStatus",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "getPlatformFee",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "pure",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "platformAddress",
		"outputs": [
			{
				"name": "",
				"type": "address"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [],
		"name": "buyContract",
		"outputs": [],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "validFlightNumber",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"name": "maxBenefit",
				"type": "uint256"
			},
			{
				"name": "airlineCode",
				"type": "bytes32"
			},
			{
				"name": "flightNumber",
				"type": "uint256"
			},
			{
				"name": "scheduleTime",
				"type": "uint256"
			},
			{
				"name": "inputPlatformAddress",
				"type": "address"
			},
			{
				"name": "inputOracleAddress",
				"type": "address"
			}
		],
		"payable": true,
		"stateMutability": "payable",
		"type": "constructor"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "_value",
				"type": "uint256"
			}
		],
		"name": "SellerDeposit",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "_value",
				"type": "uint256"
			}
		],
		"name": "BuyerDeposit",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "_value",
				"type": "uint256"
			}
		],
		"name": "ContractBuyRefund",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "contractAddress",
				"type": "address"
			}
		],
		"name": "ContractBought",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "_value",
				"type": "uint256"
			}
		],
		"name": "ContractCreateRefund",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"name": "_from",
				"type": "address"
			},
			{
				"indexed": false,
				"name": "_maxBenefit",
				"type": "uint256"
			},
			{
				"indexed": false,
				"name": "_airlineCode",
				"type": "bytes32"
			},
			{
				"indexed": false,
				"name": "_flightNumber",
				"type": "uint256"
			}
		],
		"name": "ContractCreated",
		"type": "event"
	}
]





BIN: 
608060405260405160c08062001b01833981018060405260c08110156200002557600080fd5b508051602082015160408301516060840151608085015160a09095015193949293919290918585858585856200006364010000000062000387810204565b8611620000bc576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602681526020018062001adb6026913960400191505060405180910390fd5b6000620000d28764010000000062000393810204565b9050620000e881640100000000620003a4810204565b151562000141576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602d81526020018062001a65602d913960400191505060405180910390fd5b348111156200019c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602281526020018062001a926022913960400191505060405180910390fd5b42620001b0640100000000620006e7810204565b8503116200020a576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602781526020018062001ab46027913960400191505060405180910390fd5b600481905560058690556006859055600784905560028054600160a060020a03808616600160a060020a0319928316179092556003805485841690831617905560008054909116331790819055604080518481529051348590039392909216917f327ca9276da9073b583440165cb887319e7aeaf4003f14e92c1bbeee913e9b9c9181900360200190a260008054604051600160a060020a039091169183156108fc02918491818181858888f19350505050158015620002ce573d6000803e3d6000fd5b50600054604080518381529051600160a060020a03909216917fb54ecacfeaef46d29d83a7ee9ffaae207283e8a0f5df648dba2d52a1454e489e9181900360200190a26000546004546005546006546040805193845260208401929092528282015251600160a060020a03909216917fa69e4d6d341ab4bade90446c2f1c79f5dc63aa823188d58c53696f923ab0ef099181900360600190a250506008805461ffff1916905550620007fd9a5050505050505050505050565b674563918244f4000090565b674563918244f40000908190040290565b600080620003bc8382640100000000620006ee810204565b811015620003dd57620003da836000640100000000620006ee810204565b90505b620003f3836001640100000000620006ee810204565b811015620004145762000411836001640100000000620006ee810204565b90505b6200042a836002640100000000620006ee810204565b8110156200044b5762000448836002640100000000620006ee810204565b90505b62000461836003640100000000620006ee810204565b81101562000482576200047f836003640100000000620006ee810204565b90505b62000498836004640100000000620006ee810204565b811015620004b957620004b6836004640100000000620006ee810204565b90505b620004cf836005640100000000620006ee810204565b811015620004f057620004ed836005640100000000620006ee810204565b90505b62000506836006640100000000620006ee810204565b811015620005275762000524836006640100000000620006ee810204565b90505b6200053d836007640100000000620006ee810204565b8110156200055e576200055b836007640100000000620006ee810204565b90505b62000574836008640100000000620006ee810204565b811015620005955762000592836008640100000000620006ee810204565b90505b620005ab836009640100000000620006ee810204565b811015620005cc57620005c9836009640100000000620006ee810204565b90505b620005e283600a640100000000620006ee810204565b81101562000603576200060083600a640100000000620006ee810204565b90505b6200061983600b640100000000620006ee810204565b8110156200063a576200063783600b640100000000620006ee810204565b90505b6200065083600c640100000000620006ee810204565b81101562000671576200066e83600c640100000000620006ee810204565b90505b6200068783600d640100000000620006ee810204565b811015620006a857620006a583600d640100000000620006ee810204565b90505b620006be83600e640100000000620006ee810204565b811015620006df57620006dc83600e640100000000620006ee810204565b90505b909114919050565b6201518090565b6000600882600e811115620006ff57fe5b1480620007185750600982600e8111156200071657fe5b145b80620007305750600a82600e8111156200072e57fe5b145b80620007485750600b82600e8111156200074657fe5b145b80620007605750600c82600e8111156200075e57fe5b145b80620007785750600d82600e8111156200077657fe5b145b80620007905750600e82600e8111156200078e57fe5b145b15620007a3576001835b049050620007f7565b600282600e811115620007b257fe5b1415620007c2576002836200079a565b600082600e811115620007d157fe5b1415620007f357620007eb64010000000062000387810204565b9050620007f7565b5060005b92915050565b611258806200080d6000396000f3fe6080604052600436106101445760003560e060020a90048063a89ae4ba116100ba578063c974402911610073578063c974402914610328578063d7606c411461033d578063d97939eb14610370578063dbe55e561461039a578063de866db1146103af578063e329f613146103b757610144565b8063a89ae4ba1461026d578063ab76951214610282578063b7213b52146102af578063c0dbdfa0146102d9578063c6ee20d2146102ee578063c95c8a8e1461031357610144565b80633e9ee9e51161010c5780633e9ee9e5146101ab5780635e4ff9b7146101c85780636f09caed146101f55780637150d8ae1461022e57806392e4a9ea14610243578063996b6fc11461025857610144565b806308551a53146101495780630a9020271461017a57806311da60b4146101a1578063142dfaa6146101ab5780632b68bb2d146101c0575b600080fd5b34801561015557600080fd5b5061015e6103cc565b60408051600160a060020a039092168252519081900360200190f35b34801561018657600080fd5b5061018f6103db565b60408051918252519081900360200190f35b6101a96103e1565b005b3480156101b757600080fd5b5061018f610840565b6101a9610847565b3480156101d457600080fd5b506101a9600480360360208110156101eb57600080fd5b503560ff16610948565b34801561020157600080fd5b5061020a610ab7565b6040518082600e81111561021a57fe5b60ff16815260200191505060405180910390f35b34801561023a57600080fd5b5061015e610ac5565b34801561024f57600080fd5b5061018f610ad4565b34801561026457600080fd5b5061018f610adb565b34801561027957600080fd5b5061015e610ae2565b34801561028e57600080fd5b506101a9600480360360208110156102a557600080fd5b503560ff16610af1565b3480156102bb57600080fd5b5061018f600480360360208110156102d257600080fd5b5035610c43565b3480156102e557600080fd5b5061018f610c54565b3480156102fa57600080fd5b50610303610c5a565b6040518082600481111561021a57fe5b34801561031f57600080fd5b5061018f610c63565b34801561033457600080fd5b5061018f610c69565b34801561034957600080fd5b5061018f6004803603604081101561036057600080fd5b508035906020013560ff16610c75565b34801561037c57600080fd5b5061018f6004803603602081101561039357600080fd5b5035610d64565b3480156103a657600080fd5b5061015e610d6b565b6101a9610d7a565b3480156103c357600080fd5b5061018f610fd0565b600054600160a060020a031681565b60045481565b426103ea610adb565b600754011061042d5760405160e560020a62461bcd0281526004018080602001828103825260438152602001806111ea6043913960600191505060405180910390fd5b600260085460ff16600481111561044057fe5b148061045c5750600160085460ff16600481111561045a57fe5b145b151561049c5760405160e560020a62461bcd02815260040180806020018281038252602e815260200180611152602e913960400191505060405180910390fd5b600354604080517f8da5cb5b0000000000000000000000000000000000000000000000000000000081529051600160a060020a03909216916000918391638da5cb5b91600480820192602092909190829003018186803b1580156104ff57600080fd5b505afa158015610513573d6000803e3d6000fd5b505050506040513d602081101561052957600080fd5b505160045460085491925030319160009161054b91610100900460ff16610c75565b9182900391905080156106b857600061056382610d64565b6002546040519382900393919250600160a060020a03169082156108fc029083906000818181858888f193505050501580156105a3573d6000803e3d6000fd5b506000600854610100900460ff16600e8111156105bc57fe5b1461067757600085600160a060020a03166329e2caad846040518263ffffffff1660e060020a0281526004018082815260200191505060206040518083038186803b15801561060a57600080fd5b505afa15801561061e573d6000803e3d6000fd5b505050506040513d602081101561063457600080fd5b50516040519381900393909150600160a060020a0386169082156108fc029083906000818181858888f19350505050158015610674573d6000803e3d6000fd5b50505b600154604051600160a060020a039091169083156108fc029084906000818181858888f193505050501580156106b1573d6000803e3d6000fd5b50506107e7565b60006106ca6106c5610c69565b610d64565b6002546040519482900394919250600160a060020a03169082156108fc029083906000818181858888f1935050505015801561070a573d6000803e3d6000fd5b506000600854610100900460ff16600e81111561072357fe5b146107e557600085600160a060020a03166329e2caad610741610c69565b6040518263ffffffff1660e060020a0281526004018082815260200191505060206040518083038186803b15801561077857600080fd5b505afa15801561078c573d6000803e3d6000fd5b505050506040513d60208110156107a257600080fd5b50516040519481900394909150600160a060020a0386169082156108fc029083906000818181858888f193505050501580156107e2573d6000803e3d6000fd5b50505b505b80820391801561082c5760008054604051600160a060020a039091169183156108fc02918491818181858888f1935050505015801561082a573d6000803e3d6000fd5b505b50506008805460ff19166003179055505050565b6201518090565b600054600160a060020a031633146108935760405160e560020a62461bcd0281526004018080602001828103825260238152602001806110f76023913960400191505060405180910390fd5b600060085460ff1660048111156108a657fe5b146108fb576040805160e560020a62461bcd02815260206004820152601f60248201527f636f6e747261637420737461747573206e65656420746f206265206f70656e00604482015290519081900360640190fd5b60088054600460ff1990911617905560008054604051600160a060020a0390911691303180156108fc02929091818181858888f19350505050158015610945573d6000803e3d6000fd5b50565b600354600160a060020a031633146109945760405160e560020a62461bcd0281526004018080602001828103825260288152602001806111c26028913960400191505060405180910390fd5b4261099d610840565b60075401106109e05760405160e560020a62461bcd0281526004018080602001828103825260448152602001806110436044913960600191505060405180910390fd5b426109e9610ad4565b600754011015610a2d5760405160e560020a62461bcd0281526004018080602001828103825260438152602001806110876043913960600191505060405180910390fd5b600160085460ff166004811115610a4057fe5b14610a7f5760405160e560020a62461bcd02815260040180806020018281038252602d8152602001806110ca602d913960400191505060405180910390fd5b6008805482919061ff00191661010083600e811115610a9a57fe5b0217905550600880546002919060ff19166001835b021790555050565b600854610100900460ff1681565b600154600160a060020a031681565b6203f48090565b6205460090565b600354600160a060020a031681565b600354600160a060020a03163314610b3d5760405160e560020a62461bcd028152600401808060200182810382526028815260200180610fd76028913960400191505060405180910390fd5b42610b46610ad4565b6007540110610b895760405160e560020a62461bcd0281526004018080602001828103825260428152602001806111806042913960600191505060405180910390fd5b42610b92610adb565b600754011015610bd65760405160e560020a62461bcd028152600401808060200182810382526044815260200180610fff6044913960600191505060405180910390fd5b600260085460ff166004811115610be957fe5b14610c285760405160e560020a62461bcd02815260040180806020018281038252602e815260200180611152602e913960400191505060405180910390fd5b6008805482919061ff00191661010083600e811115610aaf57fe5b674563918244f40000908190040290565b60075481565b60085460ff1681565b60055481565b674563918244f4000090565b6000600882600e811115610c8557fe5b1480610c9c5750600982600e811115610c9a57fe5b145b80610cb25750600a82600e811115610cb057fe5b145b80610cc85750600b82600e811115610cc657fe5b145b80610cde5750600c82600e811115610cdc57fe5b145b80610cf45750600d82600e811115610cf257fe5b145b80610d0a5750600e82600e811115610d0857fe5b145b15610d1b576001835b049050610d5e565b600282600e811115610d2957fe5b1415610d3757600283610d13565b600082600e811115610d4557fe5b1415610d5a57610d53610c69565b9050610d5e565b5060005b92915050565b6064900490565b600254600160a060020a031681565b610d82610c69565b341015610dd9576040805160e560020a62461bcd02815260206004820152601e60248201527f696e73756666696369656e742066756e6420666f72207072656d69756d210000604482015290519081900360640190fd5b42610de2610840565b6007540311610e255760405160e560020a62461bcd02815260040180806020018281038252603881526020018061111a6038913960400191505060405180910390fd5b600060085460ff166004811115610e3857fe5b14610e8d576040805160e560020a62461bcd02815260206004820152601f60248201527f636f6e747261637420737461747573206e65656420746f206265206f70656e00604482015290519081900360640190fd5b6001805473ffffffffffffffffffffffffffffffffffffffff19163317905534610eb5610c69565b600154910390600160a060020a03167f17c2f3e0d2d7ead2d68931154e83b5320959605ec7397093a1bd845a60e29c47610eed610c69565b60408051918252519081900360200190a2600154604051600160a060020a039091169082156108fc029083906000818181858888f19350505050158015610f38573d6000803e3d6000fd5b50600154604080518381529051600160a060020a03909216917fd6457c06d7a832c2724560b589156fc0a34d1eea0aae901b1e12d5e279a8f99a9181900360200190a2600154604080513081529051600160a060020a03909216917f596bcc7183bdee7c7371c9072d6e4c6b30dea4f278756da86ed4ec7e471c48409181900360200190a2600880546001919060ff19168280610aaf565b6006548156fe6f6e6c7920726567697374726564206f7261636c652063616e206368616e676520726573756c742173686f756c64206368616e6765206265666f726520287363686564756c655f74616b655f6f66665f74696d65202b20656e645f646973707574655f696e74657276616c2973686f756c64207265706f727420616674657220287363686564756c655f74616b655f6f66665f74696d65202b2073746172745f7265706f72745f696e74657276616c2973686f756c64207265706f7274206265666f726520287363686564756c655f74616b655f6f66665f74696d65202b20656e645f7265706f72745f696e74657276616c29636f6e747261637420737461747573206e65656420746f2062652077616974696e6720666f72207265706f72746f6e6c79206f776e65722063616e2063616e63656c207468697320636f6e747261637473686f756c64206275792067657446726f7a656e506572696f64206265666f7265207363686564756c652074616b65206f66662074696d65636f6e747261637420737461747573206e65656420746f2062652077616974696e6720666f72206469737075746573686f756c64206368616e676520616674657220287363686564756c655f74616b655f6f66665f74696d65202b20656e645f7265706f72745f696e74657276616c296f6e6c7920726567697374726564206f7261636c652063616e207265706f727420726573756c742173686f756c6420736574746c6520616674657220287363686564756c655f74616b655f6f66665f74696d65202b20656e645f646973707574655f696e74657276616c29a165627a7a72305820eab282e86a9fcfb9be1364ba06256f2b5ee4206be481a1b67941c661704ee79f00297265616c206d61782062656e656669742073686f756c6420657175616c20746f206d61782062656e6566697421696e73756666696369656e7420696e697469616c206465706f7369742066756e64217363686564756c652074616b65206f66662074696d652073686f756c64206174206c65617374206d61782062656e656669742073686f756c64206c6172676572207468616e207072656d69756d

**Comment by xiaxiangzhou** [comment]
@nmhung1210 
an example of input

![Screen Shot 2019-10-02 at 11 15 03 PM](https://user-images.githubusercontent.com/7810601/66103447-a8098100-e56a-11e9-8248-37fe8af8e0a1.png)

**Comment by xiaxiangzhou** [comment]
@nmhung1210 
This is the failed execution, notice that the value is 0 value while I actually set it to be 10 Iotex

![Screen Shot 2019-10-02 at 11 17 47 PM](https://user-images.githubusercontent.com/7810601/66103538-f3239400-e56a-11e9-9e39-934a8e053dc0.png)
