### ISSUE TITLE
bump proto defs of iotex-proto

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-antenna#374]
https://github.com/iotexproject/iotex-proto/blob/master/proto/api/read_state.proto

**Comment by puncsky** [comment]
any progress here? @ququzone

**Comment by ququzone** [comment]
> any progress here? @ququzone

wait rpc api, currently only  `ReadStakingDataRequest` is defined

**Comment by puncsky** [comment]
could you attach a task that is tracking the dependency? who is working on this?
