### ISSUE TITLE
add browser-rpc-method GetReceiptByAction

### ISSUE THREAD

**Issue by xiaxiangzhou** [iotexproject/iotex-antenna#40]
call 'http://35.192.119.63:31501' for unit test.

run the test

```js
npm run ava ./src/rpc-method/__test__/browser-rpc-method.test.js
```

this task is to implement `GetReceiptByAction ` below by following the `GetAccount` example. you can check the proto endpoint in `src/proto/api.proto`

```protobuf
    // get receipt by action Hash
	rpc GetReceiptByAction(GetReceiptByActionRequest) returns (GetReceiptByActionResponse) {}
```

node implementation for `GetReceiptByAction `: https://github.com/iotexproject/iotex-antenna/blob/master/src/rpc-method/node-rpc-method.js#L66

**Comment by knightcnbj** [comment]
we can close this one since we already merged
