### ISSUE TITLE
Building error with scrypt not found.

### ISSUE THREAD

**Issue by ZQ-jhon** [iotexproject/iotex-antenna#401]
![image](https://user-images.githubusercontent.com/26297704/97070488-31bf3d00-160b-11eb-82cc-363ac34cb27f.png)

**Comment by ququzone** [comment]
this may be an OS issue, you can reinstall all dependencies by npm. Below link is scrypt install guide.
https://www.npmjs.com/package/scrypt#windows

**Comment by ZQ-jhon** [comment]
Sure, it's an issue of my OS system.
