### ISSUE TITLE
add browser-rpc-method EstimateGasForAction

### ISSUE THREAD

**Issue by xiaxiangzhou** [iotexproject/iotex-antenna#45]
call 'http://35.192.119.63:31501' for unit test.

run the test

```js
npm run ava ./src/rpc-method/__test__/browser-rpc-method.test.js
```

this task is to implement `EstimateGasForAction ` below by following the `GetAccount` example. you can check the proto endpoint in `src/proto/api.proto`

```protobuf
    // estimate gas for action
	rpc EstimateGasForAction(EstimateGasForActionRequest) returns (EstimateGasForActionResponse) {}
```

**Comment by knightcnbj** [comment]
i'm working on this one

**Comment by knightcnbj** [comment]
there isn't anying related to `estimateGasForAction` in types.js
do u need to define those interface and property myself?

**Comment by knightcnbj** [comment]
@puncsky @xiaxiangzhou  since we've already merged the pr, can we close this issue

**Comment by xiaxiangzhou** [comment]
@knightcnbj  yeah
